version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: structsense-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:password@timescaledb:5432/iot
    depends_on:
      timescaledb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/docs" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8000:8000"
    networks:
      - structsense-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: structsense-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Important for Next.js to work correctly in Docker
      - HOSTNAME=0.0.0.0
    restart: always
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - structsense-network

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_DB: iot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d iot" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - structsense-network

volumes:
  timescale_data:
    name: structsense_timescale_data

networks:
  structsense-network:
    driver: bridge
